version: '3.1'
services:
  app:
    container_name: app
    image: 'docker-spring-boot-postgres:latest'
    build: .
    ports:
    - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/TippspielDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=post
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  postgresqldb:
    image: postgres
    container_name: db
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=post
      - POSTGRES_USER=postgres
      - POSTGRES_DB=TippspielDB
  angular:
    container_name: angular
    ports:
      - 80:80
    image: saschabrockel/docker-spring-angular:frontend
    restart: unless-stopped
    environment:
      API_URL: http://localhost:8080
      TZ: Europe/Berlin
    
